# Generated by Django 4.1 on 2022-08-19 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcentro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='Nacimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='Inicio',
            field=models.DateField(),
        ),
    ]
