# Generated by Django 4.1 on 2022-08-20 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcentro', '0002_alter_alumnos_nacimiento_alter_cursos_inicio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nacionalidad',
            old_name='Nacionalidadd',
            new_name='Nacionalidad',
        ),
    ]
