# Generated by Django 4.1 on 2022-08-24 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcentro', '0004_alter_alumnos_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnos',
            name='Sexo',
            field=models.CharField(default='none', max_length=15),
        ),
    ]
