# Generated by Django 4.1 on 2022-08-24 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcentro', '0005_alumnos_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='Sexo',
            field=models.CharField(max_length=15),
        ),
    ]
